name: 'release-to-branch'
description: 'Action that releases files and directories to a branch'
author: CDQ AG

branding:
  icon: 'git-branch'
  color: 'green'

inputs:
  branch:
    description: 'Destination branch'
    required: true

  dirs:
    description: 'Space-separated list of directories to release'
    default: 'src'

  files:
    description: 'Space-separated list of files (may be regexp) to be copied'
    default: 'action.ya?ml LICENSE README.md'

  exclude:
    description: 'Space-separated list of names to exclude (note: .git is always excluded)'
    default: ''

runs:
  using: composite
  steps:
    - run: ./src/release.sh
      shell: bash
      working-directory: ${{ github.action_path }}
      env:
        ROOT_PATH: ${{ github.workspace }}
        BRANCH: ${{ inputs.branch }}
        DIRS: ${{ inputs.dirs }}
        FILES: ${{ inputs.files }}
        EXCLUDE: ${{ inputs.exclude }}
