name: 📦 Release

on:
  push:
    branches:
    - master
    paths-ignore:
    - .cdq/**

jobs:
  test:
    uses: ./.github/workflows/test.yaml
  release:
    needs: test
    uses: cdqag/workflow-public/.github/workflows/release-action.yaml@v1
    with:
      runs-on: ubuntu-latest
